### ISSUE TITLE
frame feature extraction

### ISSUE THREAD

**Issue by rotsarak-kang** [cadt-g6/khmer_fingerspelling#1]

**Comment by theachoem** [comment]
![374](https://user-images.githubusercontent.com/29684683/204097524-812082bf-f526-44ad-baba-e34a512249b9.jpg)

**Comment by theachoem** [comment]
![Group 1](https://user-images.githubusercontent.com/29684683/204102649-185c05a5-98f5-457e-9fa1-cc08ad4c3168.png)

**Comment by theachoem** [comment]
![108](https://user-images.githubusercontent.com/29684683/204948945-cefc551d-572e-4333-bbec-5a4f2b9706f7.jpg)
